/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in managed projects and kept here so the
// repository type-checks before the first local dev run.

