services:
  - type: web
    name: parkflow-api
    runtime: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: JWT_SECRET
        value: parkflow_2026_ultra_secure_jwt_secret
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
