package br.com.parkflow.enums;

public enum TimelineEventType {
    OCORRENCIA_CRIADA,
    STATUS_ALTERADO,
    PRIORIDADE_ALTERADA,
    EVIDENCIA_ADICIONADA,
    DOCUMENTO_ADICIONADO,
    IA_ANALISOU,
    ALERTA_GERADO,
    CONSULTA_PLACA,
    COMENTARIO,
    ENCAMINHAMENTO
}
